### ISSUE TITLE
[Android BootCamp] Project2 (Gaetane Julmiste)

### ISSUE THREAD

**Issue by julmisteg** [julmisteg/NY#1]
Please Review @codepathreview @codepath

**Comment by cbaja** [comment]
I saw that you updted the readme. Is everything is ok.

@julmisteg

**Comment by cbaja** [comment]
Good Job.

@julmisteg

**Comment by cbaja** [comment]
## Week 2: New York Times News Article Search
- Consider cleaning up your search activity such as re-using a single method for both initial load and pagination
- Your pagination is **incorrect** because "start" param should be page number.
- Nice to see you added the search box to the ActionBar!
- Good to see you used a filters object to represent the filters to apply to the query
- One thing to consider is rather than sending and returning all the filter values separately as keys, might have introduced a serializable model (i.e `SearchFilters.java`) representing all the filters which were passed back and forth between activities within the bundle.
- Consider adding the ability to [share a news article](http://guides.codepath.com/android/Sharing-Content-with-Intents). This is an important learning for this assignment even though it's optional.
- Make sure to try out creating a [date picker](http://guides.codepath.com/android/Using-DialogFragment#displaying-date-or-time-picker-dialogs) dialog.
- Consider trying out the [RecyclerView](http://guides.codepath.com/android/Using-the-RecyclerView), the successor to the ListView and GridView.  
- Try out the third-party [ButterKnife](https://guides.codepath.com/android/Reducing-View-Boilerplate-with-Butterknife) library to simplify a lot of boilerplate `findViewById()` calls.

@julmisteg
